const config = [
    {
        id: 1,
        category: 'men',
        brand: "Tommy Hilfiger",
        title:  "Men's Ref Low-Top Sneakers",
        details:  "A water-resistant finish to the Ref sneakers from Tommy Hilfiger brings go-anywhere appeal to these sporty low-top lace-ups", 
        productFeatures: ['Rounded moc toe','Lace-up closure with metal eyelets' , 'Padded collar', 'Water resistant', 'Leather upper; rubber sole', 'Imported', 'ID: 530158'],
        price:  70.00,
        sizes: ['7' ,'8', "9", "10", '11'],
        imgId: "img1"
    },
    {
        id: 2,
        category: 'men',
        brand: "Cole Haan",
        title:  "Men's GrandPro Tennis Sneaker",
        details:  "Express your individual style with these hand-stained leather tennis shoes from Cole Haan.", 
        productFeatures: ['Rounded moc toe','Lace-up closure with metal eyelets' , 'Padded collar', 'Water resistant', 'Leather upper; rubber sole', 'Imported', 'ID: 2824452'],
        price:  55.00,
        sizes: ['7' ,'8', "9", "10", '11'],
        imgId: "img2"
    },
    {
        id: 3,
        category: 'men',
        brand: "Levi's",
        title:  "Men's Ethan Denim II Sneakers",
        details:  "Introduce classic casual style to your footwear collection with the cool denim uppers of these lace-up sneakers by Levi's®.", 
        productFeatures: ['Rounded moc toe','Lace-up closure with metal eyelets' , 'Padded collar', 'Water resistant', 'Leather upper; rubber sole', 'Imported', 'ID: 2824452'],
        price:  50.00,
        sizes: ['7' ,'8', "9", "10", '11'],
        imgId: "img3"
    },
    {
        id: 4,
        category: 'men',
        brand: "Steve Madden",
        title:  "Men's Frazier High-Top Sneakers",
        details:  "Introduce classic casual style to your footwear collection with the cool denim uppers of these lace-up sneakers by Levi's®.", 
        productFeatures: ['Plain toe','Lace-up closure with metal eyelets' , 'Manmade upper; rubber sole', 'Water resistant', 'Leather upper; rubber sole', 'Imported', 'ID: 630781'],
        price:  170.00,
        sizes: ['7' ,'8', "9", "10", '11'],
        imgId: "img4"
    },
    {
        id: 5,
        category: 'men',
        brand: "Ecco",
        title:  "Men's Soft 7 Sneakers",
        details:  "Ecco designed the Soft 7 Sneakers to deliver a full anatomical shape and a supremely comfortable fit and then finished them with a full-leather lining to ensure a perfect inner climate.", 
        productFeatures: ['Plain toe','Lace-up closure with metal eyelets' , 'Manmade upper; rubber sole', 'Water resistant', 'Leather upper; rubber sole', 'Imported', 'ID: 630781'],
        price:  110.00,
        sizes: ['7' ,'8',"8W" ,"9"],
        imgId: "img5"
    },
    {
        id: 6,
        category: 'men',
        brand: "Tommy Hilfiger",
        title:  "Men's Paris Sneakers",
        details:  "Fun, sporty arrives from Tommy Hilfiger and these low-top lace-up sneakers styled in the brand's iconic red, white and blue at the upper.", 
        productFeatures: ['Plain toe','Lace-up closure with metal eyelets' , 'Manmade upper; rubber sole', 'Water resistant', 'Leather upper; rubber sole', 'Savings Based On Offering Prices, Not Actual Sales', 'ID: 753085'],
        price:  220.00,
        sizes: ['7' ,'8',"8W" ,"9"],
        imgId: "img6"
    },
    {
        id: 7,
        category: 'men',
        brand: "Levi's",
        title:  "Men's Ethan Nappa Sneakers",
        details:  "Cool and casual, the smooth faux-leather uppers of the Ethan sneakers from Levi's® find their perfect finish in the antique brass eyelets at the classic lace-up closure.", 
        productFeatures: ['Plain toe','Lace-up closure with metal eyelets' , 'Manmade upper; rubber sole', 'Water resistant', 'Leather upper; rubber sole', 'Savings Based On Offering Prices, Not Actual Sales', 'ID: 856420'],
        price:  99.00,
        sizes: ['7W' ,'8',"8W" ,"9"],
        imgId: "img7"
    },
    {
        id: 8,
        category: 'men',
        brand: "Levi's",
        title:  "Men's Redd2 Lace-Up Sneakers",
        details:  "Tommy Hilfiger presents cool, comfortable style to round out your casual look with the Redd2 sneakers, designed with a low-top profile, lace-up closure and logo detail at the tongue and heel.", 
        productFeatures: ['Plain toe','Lace-up closure with metal eyelets' , 'Manmade upper; rubber sole', 'Water resistant', 'Leather upper; rubber sole', 'Savings Based On Offering Prices, Not Actual Sales', 'ID: 455648'],
        price:  70.00,
        sizes: ['7W' ,'8',"8W" ,"9"],
        imgId: "img8"
    },
    {
        id: 9,
        category: 'men',
        brand: "Cole Haan",
        title:  "Men's GrandPro Tennis Sneaker",
        details:  "Express your individual style with these hand-stained leather tennis shoes from Cole Haan.", 
        productFeatures: ['Plain toe','Lace-up closure with metal eyelets' , 'Manmade upper; rubber sole', 'Water resistant', 'Leather upper; rubber sole', 'Savings Based On Offering Prices, Not Actual Sales', 'ID: 2824452'],
        price:  70.00,
        sizes: ['7W' ,'8',"8W" ,"9"],
        imgId: "img9"
    },
    {
        id: 10,
        category: 'men',
        brand: "G-STAR",
        title:  "G-STAR classic Sneaker",
        details:  "Express your individual style with these hand-stained leather tennis shoes from Cole Haan.", 
        productFeatures: ['Plain toe','Lace-up closure with metal eyelets' , 'Manmade upper; rubber sole', 'Water resistant', 'Leather upper; rubber sole', 'Savings Based On Offering Prices, Not Actual Sales', 'ID: 2824452'],
        price:  90.00,
        sizes: ['7W' ,'8',"8W" ,"9"],
        imgId: "img10"
    },
    {
        id: 11,
        category: 'women',
        brand: "Cole Haan",
        title:  "Women's GrandPro Tennis Sneaker",
        details:  "Express your individual style with these hand-stained leather tennis shoes from Cole Haan.", 
        productFeatures: ['Rounded moc toe','Lace-up closure with metal eyelets' , 'Padded collar', 'Water resistant', 'Leather upper; rubber sole', 'Imported', 'ID: 2824452'],
        price:  55.00,
        sizes: ['7' ,'8', "9", "10", '11'],
        imgId: "img2"
    },
    {
        id: 12,
        category: 'women',
        brand: "Levi's",
        title:  "Women's Redd2 Lace-Up Sneakers",
        details:  "Tommy Hilfiger presents cool, comfortable style to round out your casual look with the Redd2 sneakers, designed with a low-top profile, lace-up closure and logo detail at the tongue and heel.", 
        productFeatures: ['Plain toe','Lace-up closure with metal eyelets' , 'Manmade upper; rubber sole', 'Water resistant', 'Leather upper; rubber sole', 'Savings Based On Offering Prices, Not Actual Sales', 'ID: 455648'],
        price:  70.00,
        sizes: ['7W' ,'8',"8W" ,"9"],
        imgId: "img8"
    },
    {
        id: 13,
        category: 'women',
        brand: "Levi's",
        title:  "Women's Ethan Nappa Sneakers",
        details:  "Cool and casual, the smooth faux-leather uppers of the Ethan sneakers from Levi's® find their perfect finish in the antique brass eyelets at the classic lace-up closure.", 
        productFeatures: ['Plain toe','Lace-up closure with metal eyelets' , 'Manmade upper; rubber sole', 'Water resistant', 'Leather upper; rubber sole', 'Savings Based On Offering Prices, Not Actual Sales', 'ID: 856420'],
        price:  99.00,
        sizes: ['7W' ,'8',"8W" ,"9"],
        imgId: "img7"
    },
    {
        id: 14,
        category: 'kids',
        brand: "Tommy Hilfiger",
        title:  "Kids Paris Sneakers",
        details:  "Fun, sporty arrives from Tommy Hilfiger and these low-top lace-up sneakers styled in the brand's iconic red, white and blue at the upper.", 
        productFeatures: ['Plain toe','Lace-up closure with metal eyelets' , 'Manmade upper; rubber sole', 'Water resistant', 'Leather upper; rubber sole', 'Savings Based On Offering Prices, Not Actual Sales', 'ID: 753085'],
        price:  40.00,
        sizes: ['7' ,'8',"8W" ,"9"],
        imgId: "img6"
    },
    {
        id: 15,
        category: 'kids',
        brand: "Steve Madden",
        title:  "Kids Frazier High-Top Sneakers",
        details:  "Introduce classic casual style to your footwear collection with the cool denim uppers of these lace-up sneakers by Levi's®.", 
        productFeatures: ['Plain toe','Lace-up closure with metal eyelets' , 'Manmade upper; rubber sole', 'Water resistant', 'Leather upper; rubber sole', 'Imported', 'ID: 630781'],
        price:  45.00,
        sizes: ['7' ,'8', "9", "10", '11'],
        imgId: "img4"
    },
    {
        id: 16,
        category: 'kids',
        brand: "Levi's",
        title:  "Kids Ethan Denim II Sneakers",
        details:  "Introduce classic casual style to your footwear collection with the cool denim uppers of these lace-up sneakers by Levi's®.", 
        productFeatures: ['Rounded moc toe','Lace-up closure with metal eyelets' , 'Padded collar', 'Water resistant', 'Leather upper; rubber sole', 'Imported', 'ID: 2824452'],
        price: 39.00,
        sizes: ['7' ,'8', "9", "10", '11'],
        imgId: "img3"
    },
    {
        id: 17,
        category: 'kids',
        brand: "Levi's",
        title:  "Kids Ethan Denim II Sneakers",
        details:  "Introduce classic casual style to your footwear collection with the cool denim uppers of these lace-up sneakers by Levi's®.", 
        productFeatures: ['Rounded moc toe','Lace-up closure with metal eyelets' , 'Padded collar', 'Water resistant', 'Leather upper; rubber sole', 'Imported', 'ID: 2824452'],
        price: 39.00,
        sizes: ['7' ,'8', "9", "10", '11'],
        imgId: "img11"
    },
    {
        id: 18,
        category: 'kids',
        brand: "Levi's",
        title:  "Kids Ethan Denim II Sneakers",
        details:  "Introduce classic casual style to your footwear collection with the cool denim uppers of these lace-up sneakers by Levi's®.", 
        productFeatures: ['Rounded moc toe','Lace-up closure with metal eyelets' , 'Padded collar', 'Water resistant', 'Leather upper; rubber sole', 'Imported', 'ID: 2824452'],
        price: 39.00,
        sizes: ['7' ,'8', "9", "10", '11'],
        imgId: "img12"
    },
    {
        id: 19,
        category: 'kids',
        brand: "Levi's",
        title:  "Kids Ethan Denim II Sneakers",
        details:  "Introduce classic casual style to your footwear collection with the cool denim uppers of these lace-up sneakers by Levi's®.", 
        productFeatures: ['Rounded moc toe','Lace-up closure with metal eyelets' , 'Padded collar', 'Water resistant', 'Leather upper; rubber sole', 'Imported', 'ID: 2824452'],
        price: 39.00,
        sizes: ['7' ,'8', "9", "10", '11'],
        imgId: "img13"
    },
    {
        id: 20,
        category: 'kids',
        brand: "Levi's",
        title:  "Kids Ethan Denim II Sneakers",
        details:  "Introduce classic casual style to your footwear collection with the cool denim uppers of these lace-up sneakers by Levi's®.", 
        productFeatures: ['Rounded moc toe','Lace-up closure with metal eyelets' , 'Padded collar', 'Water resistant', 'Leather upper; rubber sole', 'Imported', 'ID: 2824452'],
        price: 39.00,
        sizes: ['7' ,'8', "9", "10", '11'],
        imgId: "img14"
    },
    {
        id: 21,
        category: 'kids',
        brand: "Levi's",
        title:  "Kids Ethan Denim II Sneakers",
        details:  "Introduce classic casual style to your footwear collection with the cool denim uppers of these lace-up sneakers by Levi's®.", 
        productFeatures: ['Rounded moc toe','Lace-up closure with metal eyelets' , 'Padded collar', 'Water resistant', 'Leather upper; rubber sole', 'Imported', 'ID: 2824452'],
        price: 39.00,
        sizes: ['7' ,'8', "9", "10", '11'],
        imgId: "img15"
    },
    {
        id: 22,
        category: 'women',
        brand: "Levi's",
        title:  "Women's Redd2 Lace-Up Sneakers",
        details:  "Tommy Hilfiger presents cool, comfortable style to round out your casual look with the Redd2 sneakers, designed with a low-top profile, lace-up closure and logo detail at the tongue and heel.", 
        productFeatures: ['Plain toe','Lace-up closure with metal eyelets' , 'Manmade upper; rubber sole', 'Water resistant', 'Leather upper; rubber sole', 'Savings Based On Offering Prices, Not Actual Sales', 'ID: 455648'],
        price:  70.00,
        sizes: ['7W' ,'8',"8W" ,"9"],
        imgId: "img20"
    },
    {
        id: 23,
        category: 'women',
        brand: "Levi's",
        title:  "Women's Redd2 Lace-Up Sneakers",
        details:  "Tommy Hilfiger presents cool, comfortable style to round out your casual look with the Redd2 sneakers, designed with a low-top profile, lace-up closure and logo detail at the tongue and heel.", 
        productFeatures: ['Plain toe','Lace-up closure with metal eyelets' , 'Manmade upper; rubber sole', 'Water resistant', 'Leather upper; rubber sole', 'Savings Based On Offering Prices, Not Actual Sales', 'ID: 455648'],
        price:  70.00,
        sizes: ['7W' ,'8',"8W" ,"9"],
        imgId: "img21"
    },
    {
        id: 24,
        category: 'women',
        brand: "Levi's",
        title:  "Women's Redd2 Lace-Up Sneakers",
        details:  "Tommy Hilfiger presents cool, comfortable style to round out your casual look with the Redd2 sneakers, designed with a low-top profile, lace-up closure and logo detail at the tongue and heel.", 
        productFeatures: ['Plain toe','Lace-up closure with metal eyelets' , 'Manmade upper; rubber sole', 'Water resistant', 'Leather upper; rubber sole', 'Savings Based On Offering Prices, Not Actual Sales', 'ID: 455648'],
        price:  70.00,
        sizes: ['7W' ,'8',"8W" ,"9"],
        imgId: "img22"
    },
    {
        id: 25,
        category: 'women',
        brand: "Levi's",
        title:  "Women's Redd2 Lace-Up Sneakers",
        details:  "Tommy Hilfiger presents cool, comfortable style to round out your casual look with the Redd2 sneakers, designed with a low-top profile, lace-up closure and logo detail at the tongue and heel.", 
        productFeatures: ['Plain toe','Lace-up closure with metal eyelets' , 'Manmade upper; rubber sole', 'Water resistant', 'Leather upper; rubber sole', 'Savings Based On Offering Prices, Not Actual Sales', 'ID: 455648'],
        price:  70.00,
        sizes: ['7W' ,'8',"8W" ,"9"],
        imgId: "img23"
    },
    {
        id: 26,
        category: 'women',
        brand: "Levi's",
        title:  "Women's Redd2 Lace-Up Sneakers",
        details:  "Tommy Hilfiger presents cool, comfortable style to round out your casual look with the Redd2 sneakers, designed with a low-top profile, lace-up closure and logo detail at the tongue and heel.", 
        productFeatures: ['Plain toe','Lace-up closure with metal eyelets' , 'Manmade upper; rubber sole', 'Water resistant', 'Leather upper; rubber sole', 'Savings Based On Offering Prices, Not Actual Sales', 'ID: 455648'],
        price:  70.00,
        sizes: ['7W' ,'8',"8W" ,"9"],
        imgId: "img24"
    },
]
module.exports = config