export const GET_CATALOG = 'GET_CATALOG';
export const GET_CATALOG_PENDING = 'GET_CATALOG_PENDING';
export const GET_CATALOG_FULFILLED = 'GET_CATALOG_FULFILLED';
export const GET_CATALOG_REJECTED = 'GET_CATALOG_REJECTED';

export const GET_ITEM = 'GET_ITEM';
export const GET_ITEM_PENDING = 'GET_ITEM_PENDING';
export const GET_ITEM_FULFILLED = 'GET_ITEM_FULFILLED';
export const GET_ITEM_REJECTED = 'GET_ITEM_REJECTED';


export const CUT_CATALOG = 'CUT_CATALOG';
export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

export const SORT_DEFAULT = 'SORT_DEFAULT';
export const LOW_TO_HIGH = 'LOW_TO_HIGH';
export const HIGH_TO_LOW = 'HIGH_TO_LOW';

export const CLEAR_FILTER = 'CLEAR_FILTER';

export const ADD_TO_CART = 'ADD_TO_CART';

export const DECREMENT_CART = 'DECREMENT_CART';
export const INCREMENT_CART = 'INCREMENT_CART';
export const CHANGE_CART = 'CHANGE_CART';
export const DELETE_CART = 'DELETE_CART';


export const EDIT_ADDRESS = 'EDIT_ADDRESS';
export const EDIT_NAME = 'EDIT_NAME';
export const EDIT_PHONE = 'EDIT_PHONE';


export const CART_IS_CHANGED = 'CART_IS_CHANGED';
export const CART_IS_CHANGED_PENDING = 'CART_IS_CHANGED_PENDING';
export const CART_IS_CHANGED_FULFILLED = 'CART_IS_CHANGED_FULFILLED';
export const CART_IS_CHANGED_REJECTED = 'CART_IS_CHANGED_REJECTED';

export const LOAD_CART = 'LOAD_CART';
export const LOAD_CART_PENDING = 'LOAD_CART_PENDING';
export const LOAD_CART_REJECTED = 'LOAD_CART_REJECTED';
export const LOAD_CART_FULFILLED = 'LOAD_CART_FULFILLED';

export const LOAD_STORE_USER = 'LOAD_STORE_USER';

export const NEW_USER = 'NEW_USER';
export const LOAD_USER = 'LOAD_USER';
export const LOAD_USER_PENDING = 'LOAD_USER_PENDING';
export const LOAD_USER_REJECTED = 'LOAD_USER_REJECTED';
export const LOAD_USER_FULFILLED = 'LOAD_USER_FULFILLED';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_PENDING = 'LOGOUT_PENDING';
export const LOGOUT_REJECTED = 'LOGOUT_REJECTED';
export const LOGOUT_FULFILLED = 'LOGOUT_FULFILLED';

export const CHANGE_ADDRESS = 'CHANGE_ADDRESS';
export const CHANGE_ADDRESS_PENDING = 'CHANGE_ADDRESS_PENDING';
export const CHANGE_ADDRESS_REJECTED = 'CHANGE_ADDRESS_REJECTED';
export const CHANGE_ADDRESS_FULFILLED = 'CHANGE_ADDRESS_FULFILLED';


export const CHECKOUT = 'CHECKOUT';
export const CHECKOUT_PENDING = 'CHECKOUT_PENDING';
export const CHECKOUT_REJECTED = 'CHECKOUT_REJECTED';
export const CHECKOUT_FULFILLED = 'CHECKOUT_FULFILLED';


export const CHANGE_USER = 'CHANGE_USER';
export const CHANGE_USER_PENDING = 'CHANGE_USER_PENDING';
export const CHANGE_USER_REJECTED = 'CHANGE_USER_REJECTED';
export const CHANGE_USER_FULFILLED = 'CHANGE_USER_FULFILLED';


export const CHANGE_NAME = 'CHANGE_NAME';
export const CHANGE_NAME_PENDING = 'CHANGE_NAME_PENDING';
export const CHANGE_NAME_REJECTED = 'CHANGE_NAME_REJECTED';
export const CHANGE_NAME_FULFILLED = 'CHANGE_NAME_FULFILLED';


export const CHANGE_PHONE = 'CHANGE_PHONE';
export const CHANGE_PHONE_PENDING = 'CHANGE_PHONE_PENDING';
export const CHANGE_PHONE_REJECTED = 'CHANGE_PHONE_REJECTED';
export const CHANGE_PHONE_FULFILLED = 'CHANGE_PHONE_FULFILLED';


export const ADD_REVIEW = 'ADD_REVIEW';
export const ADD_REVIEW_PENDING = 'ADD_REVIEW_PENDING';
export const ADD_REVIEW_REJECTED = 'ADD_REVIEW_REJECTED';
export const ADD_REVIEW_FULFILLED = 'ADD_REVIEW_FULFILLED';


